### PR TITLE
support Carthage

### PR DESCRIPTION
**Pull request by takuoka**

### CODE REVIEW

**Comment by entotsu** [comment]
please merge if you ok :+1:

**Comment by PhamBaTho** [comment]
@entotsu thanks for your PR. I've been hanging this PR with the intent to make this repo more stable first and support Carthage then. It's still 0.x version. Carthage supporting might go with 1.0 release. Thanks again.

**Comment by batjo** [comment]
Would be nice if this could soon be merged

**Comment by igorkulman** [comment]
Any news on this?

**Comment by PhamBaTho** [comment]
update: Carthage has been supported!

**Pull request closed without merging**
