### PR TITLE
added property to keep title label static.

### PR DESCRIPTION
**Pull request by RishabhTayal**
Added an option to keep the title label text static. https://github.com/PhamBaTho/BTNavigationDropdownMenu/issues/18

### CODE REVIEW

**Comment by RishabhTayal** [comment]
@PhamBaTho Tested the feature. It's ready to merge.

**Comment by mirzadelic** [comment]
+1

**Comment by RishabhTayal** [comment]
@mirzadelic until this PR is merged you can use this feature by adding this to your `podfile`.

`pod 'BTNavigationDropdownMenu', :git => 'https://github.com/RishabhTayal/BTNavigationDropdownMenu.git', :branch => 'master'`

**Comment by mirzadelic** [comment]
Thanks.

**Comment by PhamBaTho** [comment]
@RishabhTayal: Nice. This PR is merged. Thanks for PR and your temporary `podfile` solution 😉

**Comment by RishabhTayal** [comment]
@PhamBaTho Thanks for releasing this in version 0.4.1 👍

**Pull request merged**
